// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBackFiles():Promise<Array<string>>;

export function GetSetImage():Promise<main.SetImage>;

export function GetWaterFiles():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectBackFiles():Promise<void>;

export function SelectWaterFiles():Promise<void>;
