// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Delimg(arg1:string,arg2:number):Promise<{[key: string]: string}>;

export function GetBackFiles():Promise<{[key: string]: string}>;

export function GetSetImage():Promise<main.SetImage>;

export function GetWaterFiles():Promise<{[key: string]: string}>;

export function SelectBackFiles():Promise<void>;

export function SelectWaterFiles():Promise<void>;

export function SetOutDir():Promise<string>;

export function Start(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;
