// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackFiles() {
  return window['go']['main']['App']['GetBackFiles']();
}

export function GetSetImage() {
  return window['go']['main']['App']['GetSetImage']();
}

export function GetWaterFiles() {
  return window['go']['main']['App']['GetWaterFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectBackFiles() {
  return window['go']['main']['App']['SelectBackFiles']();
}

export function SelectWaterFiles() {
  return window['go']['main']['App']['SelectWaterFiles']();
}

export function SetOutDir() {
  return window['go']['main']['App']['SetOutDir']();
}

export function Start(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Start'](arg1, arg2, arg3, arg4);
}
